import { Film } from "Redux/types/FilmType";
export const initialFilmList: Film[] = [
  // {
  //   maPhim: 11078,
  //   tenPhim: "Avatar: Dòng chảy của nước 4",
  //   biDanh: "avatar-dong-chay-cua-nuoc-4",
  //   trailer: "https://www.youtube.com/watch?v=gq2xKJXYZ80",
  //   hinhAnh:
  //     "http://movieapi.cyberlearn.vn/hinhanh/avatar-dong-chay-cua-nuoc_gp01.jpg",
  //   moTa: "avartar 2 dong chay nuoc",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-03-10T11:09:24.35",
  //   danhGia: 8,
  //   hot: false,
  //   dangChieu: true,
  //   sapChieu: false,
  // },
  // {
  //   maPhim: 11079,
  //   tenPhim: "Nhà bà Nữ",
  //   biDanh: "nha-ba-nu",
  //   trailer: "https://youtu.be/IkaP0KJWTsQ",
  //   hinhAnh: "http://movieapi.cyberlearn.vn/hinhanh/nha-ba-nu_gp01.jpg",
  //   moTa: "Nhà bà Nữ là một bộ phim điện ảnh chính kịch, gia đình do Trấn Thành sản xuất và làm đạo diễn. Bộ phim do Đỗ Hoàng Vũ, quản lý của Trấn Thành và Hari Won đảm nhận vai trò đồng sản xuất. Đây là bộ phim thứ hai do Trấn Thành làm đạo diễn sau Bố già, bộ phim có doanh thu cao nhất lịch sử phòng vé Việt Nam.",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-01-22T00:00:00",
  //   danhGia: 8,
  //   hot: false,
  //   dangChieu: false,
  //   sapChieu: true,
  // },
  // {
  //   maPhim: 11088,
  //   tenPhim: "SÁT THỦ JOHN WICK 2",
  //   biDanh: "sat-thu-john-wick-2",
  //   trailer: "https://www.youtube.com/watch?v=yjRHZEUamCc",
  //   hinhAnh:
  //     "http://movieapi.cyberlearn.vn/hinhanh/sat-thu-john-wick-2_gp01.jpg",
  //   moTa: "John Wick là một sát thủ khét tiếng trong giới xã hội đen. Những kẻ trong nghề thường truyền tai nhau rằng: “Hắn không phải là ác quỷ. Hắn là người được cử đi để giết ác quỷ”. Phần hai của John Wick bắt đầu khi nhân vật sát thủ máu lạnh của Keanu Reeves đặt chân tới thành phố Rome, Italy và không may đụng độ với một gã gangster khét tiếng tại đất nước này.",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-03-10T11:12:33.457",
  //   danhGia: 7,
  //   hot: false,
  //   dangChieu: true,
  //   sapChieu: false,
  // },
  // {
  //   maPhim: 11090,
  //   tenPhim: "One Piece 3",
  //   biDanh: "one-piece-3",
  //   trailer: "",
  //   hinhAnh: "http://movieapi.cyberlearn.vn/hinhanh/one-piece-1_gp01.jpg",
  //   moTa: "One Piece là bộ truyện tranh dành cho thiếu niên của tác giả nổi tiếng Oda Eiichiro. Bộ manga này được chuyển thể thành một series anime nhiều tập hài hước, đặc sắc. Phim Đảo Hải Tặc mở đầu câu chuyện bằng cảnh xử tử vua hải tặc Gol D. Roger. Trước khi chết ông đã tiết lộ rằng mình có một kho báu được giấu ngoài biển. Nếu ai tìm thấy kho báu thì chúng sẽ thuộc về người đó. Rất nhiều người gan dạ đã đổ xô ra biển để tìm kiếm kho báu bí ẩn của vua hải tặc Gol D. Roger.",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-01-09T15:50:04.02",
  //   danhGia: 8,
  //   hot: true,
  //   dangChieu: true,
  //   sapChieu: false,
  // },
  // {
  //   maPhim: 11078,
  //   tenPhim: "Avatar: Dòng chảy của nước 4",
  //   biDanh: "avatar-dong-chay-cua-nuoc-4",
  //   trailer: "https://www.youtube.com/watch?v=gq2xKJXYZ80",
  //   hinhAnh:
  //     "http://movieapi.cyberlearn.vn/hinhanh/avatar-dong-chay-cua-nuoc_gp01.jpg",
  //   moTa: "avartar 2 dong chay nuoc",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-03-10T11:09:24.35",
  //   danhGia: 8,
  //   hot: false,
  //   dangChieu: true,
  //   sapChieu: false,
  // },
  // {
  //   maPhim: 11079,
  //   tenPhim: "Nhà bà Nữ",
  //   biDanh: "nha-ba-nu",
  //   trailer: "https://youtu.be/IkaP0KJWTsQ",
  //   hinhAnh: "http://movieapi.cyberlearn.vn/hinhanh/nha-ba-nu_gp01.jpg",
  //   moTa: "Nhà bà Nữ là một bộ phim điện ảnh chính kịch, gia đình do Trấn Thành sản xuất và làm đạo diễn. Bộ phim do Đỗ Hoàng Vũ, quản lý của Trấn Thành và Hari Won đảm nhận vai trò đồng sản xuất. Đây là bộ phim thứ hai do Trấn Thành làm đạo diễn sau Bố già, bộ phim có doanh thu cao nhất lịch sử phòng vé Việt Nam.",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-01-22T00:00:00",
  //   danhGia: 8,
  //   hot: false,
  //   dangChieu: false,
  //   sapChieu: true,
  // },
  // {
  //   maPhim: 11088,
  //   tenPhim: "SÁT THỦ JOHN WICK 2",
  //   biDanh: "sat-thu-john-wick-2",
  //   trailer: "https://www.youtube.com/watch?v=yjRHZEUamCc",
  //   hinhAnh:
  //     "http://movieapi.cyberlearn.vn/hinhanh/sat-thu-john-wick-2_gp01.jpg",
  //   moTa: "John Wick là một sát thủ khét tiếng trong giới xã hội đen. Những kẻ trong nghề thường truyền tai nhau rằng: “Hắn không phải là ác quỷ. Hắn là người được cử đi để giết ác quỷ”. Phần hai của John Wick bắt đầu khi nhân vật sát thủ máu lạnh của Keanu Reeves đặt chân tới thành phố Rome, Italy và không may đụng độ với một gã gangster khét tiếng tại đất nước này.",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-03-10T11:12:33.457",
  //   danhGia: 7,
  //   hot: false,
  //   dangChieu: true,
  //   sapChieu: false,
  // },
  // {
  //   maPhim: 11090,
  //   tenPhim: "One Piece 3",
  //   biDanh: "one-piece-3",
  //   trailer: "",
  //   hinhAnh: "http://movieapi.cyberlearn.vn/hinhanh/one-piece-1_gp01.jpg",
  //   moTa: "One Piece là bộ truyện tranh dành cho thiếu niên của tác giả nổi tiếng Oda Eiichiro. Bộ manga này được chuyển thể thành một series anime nhiều tập hài hước, đặc sắc. Phim Đảo Hải Tặc mở đầu câu chuyện bằng cảnh xử tử vua hải tặc Gol D. Roger. Trước khi chết ông đã tiết lộ rằng mình có một kho báu được giấu ngoài biển. Nếu ai tìm thấy kho báu thì chúng sẽ thuộc về người đó. Rất nhiều người gan dạ đã đổ xô ra biển để tìm kiếm kho báu bí ẩn của vua hải tặc Gol D. Roger.",
  //   maNhom: "GP01",
  //   ngayKhoiChieu: "2023-01-09T15:50:04.02",
  //   danhGia: 8,
  //   hot: true,
  //   dangChieu: true,
  //   sapChieu: false,
  // },
];
