export const NGUOI_DUNG_DANG_NHAP = 'NGUOI_DUNG_DANG_NHAP';
export const NGUOI_DUNG_DANG_KY = 'NGUOI_DUNG_DANG_KY';
export const SET_DANH_SACH_NGUOI_DUNG = 'SET_DANH_SACH_NGUOI_DUNG';
export const SET_THONG_TIN_NGUOI_DUNG = 'SET_THONG_TIN_NGUOI_DUNG';
export const SET_FULL_INFO_NGUOI_DUNG = 'SET_FULL_INFO_NGUOI_DUNG';
